[package]
name = "ku-ical-renamer"
version = "0.1.0"
authors = ["Alice Ryhl <alice@ryhl.io>"]
edition = "2018"

[dependencies]
ical = "0.6"
icalendar = "0.6"
reqwest = "0.10.0-alpha.1"
tokio = "0.2.0-alpha.6"
regex = "1.3.1"
lazy_static = "1.4.0"
